### ISSUE TITLE
Menu and game projects

### ISSUE THREAD

**Issue by NLferdiNL** [IanMunster/Asteroids#1]
They belong in one project. Not two.
You're only making it harder for yourself in the long run.

**Comment by IanMunster** [comment]
Dear NLferdiNL, Thank you for the Comment;
The Menu folder is just a backup for the Menu, In the GAMEPLAY folder is the complete game.
You could also try "https://github.com/IanMunster/CometMeBro"
For the Released Code Only

**Comment by NLferdiNL** [comment]
Alright understood, we were given this repo to review.
Atleast it's clear the way it was meant now.
