### ISSUE TITLE
OOP Code

### ISSUE THREAD

**Issue by NLferdiNL** [IanMunster/Asteroids#2]
You guys made a lot of health classes.
Making one class that everything uses would make it easier to code and also reusable in later projects.

**Comment by IanMunster** [comment]
Thx! I'll take a look at the code again, to try and maken it better OOP.
- added to ToDo in Trello, scheduled for version v1.2

**Comment by IanMunster** [comment]
3 scripts found; Player, Enemy and Asteroids.
Although every script manipulates the health value in a different way
