### ISSUE TITLE
Public variables

### ISSUE THREAD

**Issue by NLferdiNL** [IanMunster/Asteroids#3]
You mostly prevented using publics, which is good practise.
I did find two publics here.
If you need outsiders to access your variables use get/set accessors and .SerialiseField.

[Accessors](https://msdn.microsoft.com/en-us/library/w86s7x04.aspx)

[SerializeField](https://docs.unity3d.com/ScriptReference/SerializeField.html)

Issue at:
```
public Transform PullOBJ;
public float ForceSpeed;

private GameObject playerShip;
private PlayerShield _playerShield;

//audio
private AudioSource source;
```
[Blackhole.cs](https://github.com/IanMunster/Asteroids/blob/master/GAMEPLAY/Assets/Scripts/LevelObjScript/Blackhole.cs)

**Comment by IanMunster** [comment]
Thank you forgot these public VARS

**Comment by IanMunster** [comment]
Done!
